### ISSUE TITLE
Keep getting database not open and iterator not open when using level in NodeEnv

### ISSUE THREAD

**Issue by kevinkyle4** [Level/community#135]
I have a simple Express server running Level and if I stop and start express sever back up a few times while testing I get issues with Lock file. How do I prevent? 

ModuleError: Database is not open
    at maybeOpened (C:\Users\kevin\did_mail_landing\node_modules\abstract-level\abstract-level.js:133:18)
    at C:\Users\kevin\did_mail_landing\node_modules\abstract-level\abstract-level.js:160:13
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'LEVEL_DATABASE_NOT_OPEN',
  cause: [Error: IO error: LockFile ./db/LOCK: The process cannot access the file because it is being used by another process.

**Comment by RioChndr** [comment]
I get the same situation, and I think this is feature of level to prevent multiple connection at once.

The trick to open the lock, rename `LOCK` file in directory of database —or just remove it.

And you should close the database when application shutting down

```ts
const shutdownSignals: NodeJS.Signals[] = ['SIGINT', 'SIGTERM', 'SIGQUIT'];
    shutdownSignals.forEach((signal) => {
      process.on(signal, async () => {
      store._db.close().then(() => {
        console.log('Session store database closed successfully');
      }).catch((err) => {
        console.error('Failed to close session store database:', err);
      });
    })
```
